modLoader="kotlinforforge"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/your-username/craftdeck/issues"

[[mods]]
modId="craftdeck"
version="${version}"
displayName="CraftDeck"
description='''
A dual-component system enabling real-time communication between Minecraft and StreamDeck devices.
'''
logoFile="craftdeck.png"
credits="CraftDeck Team"
authors="CraftDeck Contributors"

[[dependencies.craftdeck]]
modId="neoforge"
mandatory=true
versionRange="[20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.craftdeck]]
modId="architectury"
mandatory=true
versionRange="[9.1.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies.craftdeck]]
modId="kotlinforforge"
mandatory=true
versionRange="[4,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="craftdeck.mixins.json"